# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 724fc74aa0fe9b5878d8fe31bef6c4a2af90167a29be70eb5dc045093f03080fc8c86b14955b2c09ecb57ef091bca2a8cfee12c27e8be38414216d3d03976845

test:
  secret_key_base: 61d764203fabc5240a99840be7061d347fd31d8ba6df1b1628dced74f8990bce2449d1902b9ebebf90d51c71b69bc83c1d85e2cb21ab0196e7f031d957318c30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
